app/routes/reports.py
import io

from flask import Blueprint, flash, render_template, request

from crud.parse_reports import parse_report

bp = Blueprint('reports', __name__, url_prefix='/reports')


@bp.add_app_template_filter
def currency_format(value):
    return f'{value:.2f}'


@bp.route('/', methods=['GET'])
def upload():
    """Prompt the user to upload reports."""
    return render_template('report_upload.html.j2')


@bp.route('/', methods=['POST'])
def parse():
    """Parse the reports and display the results."""
    if not request.files.get('transactions') or not request.files.get('items'):
        flash('Please upload both reports required!')
        return upload()

    transactions_file = io.BytesIO(request.files['transactions'].read())
    items_file = io.BytesIO(request.files['items'].read())
    report = parse_report(transactions_file, items_file)
    return render_template('report_parse.html.j2', report=report)

app/templates/base.html.j2
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css"
    integrity="sha384-EkHEUZ6lErauT712zSr0DZ2uuCmi3DoQj6ecNdHQXpMpFNGAQ48WjfXCE5n20W+R" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/css/bootstrap-select.min.css"
    integrity="sha256-jwJEU4p1YdtymLFwAjYfam5Pj5NOnylms63k7LYQ9Jk=" crossorigin="anonymous">
  <!-- Custom CSS -->
  <style>
    body {
      padding-top: 5rem;
    }

    .starter-template {
      padding: 3rem 1.5rem;
      text-align: center;
    }
  </style>

  <title>{% block title %}Some Title{% endblock %}</title>
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <span class="navbar-brand mb-0 h2">Organizer</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" id="people-nav" href="{{ url_for('persons_table_view') }}">
            People</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="transactions-nav" href="{{ url_for('transactions_table_view') }}">
            Transactions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="add-person-nav" href="{{ url_for('add_new_person_form_view') }}">
            Add person</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="add-transaction-nav" href="{{ url_for('transactions_input_form_view') }}">
            Add transaction</a>
        </li>
        <li class="nav-item">
          {# <a class="nav-link" id="parse-reports-nav" href="{{ url_for('reports.upload') }}"> #}
            Parse reports</a>
        </li>
      </ul>
      {% block taskbar %}{% endblock %}
    </div>
  </nav>

  <main role="main" class="container">
    <!-- Page Content -->
    <div class="container">
    {# get_flashed_messages() #}
      {% with messages = [] %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-danger col-lg-12" role="alert">
              <strong>Error:</strong> {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %} {% endblock %}
    </div>

  </main>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"
    integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp"
    crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"
    integrity="sha384-uiSTMvD1kcI19sAHJDVf68medP9HA2E2PzGis9Efmfsdb8p9+mvbQNgFhzii1MEX"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.10/js/bootstrap-select.min.js"
    integrity="sha256-FXzZGmaRFZngOjUKy3lWZJq/MflaMpffBbu3lPT0izE=" 
    crossorigin="anonymous"></script>

  <script type="text/javascript">
    $(document).ready(function () {
      $(".alert").alert();
    });
  </script>
  
  {% block scripts %}{% endblock %}
</body>

</html>

app/templates/data.html.j2
<!doctype html>
<html lang="en">

<body>
  <table id="data_table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Supplier</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Notes</th>
        <th>Created at</th>
        <th>Updated at</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
      <tr>
        <td>{{ transaction.id }}</td>
        <td>{{ transaction.date }}</td>
        <td>{{ transaction.supplier }}</td>
        <td>{{ transaction.amount | currency_format }}</td>
        <td>{{ transaction.category }}</td>
        <td>{{ transaction.notes or '' }}</td>
        <td>{{ transaction.created_at }}</td>
        <td>{{ transaction.updated_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>

app/templates/edit.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function () {

        // Constructing the suggestion engine
        var categories = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.whitespace,
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            local: {{ categories| tojson | safe}}
    });
    var suppliers = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: {{ suppliers| tojson | safe}}
    });

    // Initializing the typeahead
    $('.categories').typeahead({
        hint: true,
        highlight: true,
        minLength: 1
    },
        {
            source: categories
        });
    $('.suppliers').typeahead({
        hint: true,
        highlight: true,
        minLength: 1
    },
        {
            source: suppliers
        });
  });
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 text-center">
        <h1>Hi! I'm transaction #{{ transaction['id'] }}</h1>
        <p class="lead">Would you like to edit me or add some notes?</p>
    </div>
</div>
<!-- /.row -->

<div class="row">
    <table id="table_id" class="table">
        <tbody>
            <form id="edit" method="POST"
                action="{{ url_for('transactions.update_transaction', transaction_id=transaction['id']) }}">
                <tr>
                    <th>Date</th>
                    <td><input name="day" form="edit" class="form-control" type="date"
                            value="{{ transaction['date'] }}"></td>
                    <td rowspan="4"><textarea name="notes" form="edit" class="form-control" rows="8"
                            {% if not transaction['notes'] %} placeholder="You can add notes here"
                            {% endif %}>{{ transaction['notes'] }}</textarea></td>
                </tr>
                <tr>
                    <th>Supplier</th>
                    <td><input name="supplier" form="edit" class="suppliers form-control" type="text"
                            value="{{ transaction['supplier'] }}"></td>
                </tr>
                <tr>
                    <th>Amount</th>
                    <td><input name="amount" form="edit" class="form-control" type="text"
                            value="{{ transaction['amount'] }}"></td>
                </tr>
                <tr>
                    <th>Category</th>
                    <td><input name="category" form="edit" class="categories form-control" type="text"
                            value="{{ transaction['category'] }}"></td>
                </tr>
            </form>
            <tr>
                <th>Actions</th>
                <td>
                    <input type="submit" form="edit" value="Save changes" class="btn btn-success">
                    <form style="display: inline;" method="POST"
                        action="{{ url_for('transactions.delete_transaction', transaction_id=transaction['id']) }}">
                        <input type="submit" class="btn btn-danger" value="Delete transaction">
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="row">
    <i>Last modified {{ transaction['last_modified'] }}</i>
</div>
<div class="row">
    <i>Created on {{ transaction['created_at'] }}</i>
</div>
{% endblock %}

app/templates/input.html
{% extends "base.html" %}
{% block title %}Transaction input{% endblock %}

{% block scripts %}
<script type="text/javascript">
  $(document).ready(function () {

    $("#input-nav").addClass("active");
    $("#view-nav").removeClass("active");
    $("#pivot-nav").removeClass("active");

    $("#supplier-input-id").focusout(function () {
      $.get("{{ url_for('autocomplete.category_guess', q='') }}" + $("#supplier-input-id").val(), function (data) {
        $("#category-input-id").val(data.category);
      });
    });
  });
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Latest transactions</h1>
    <p class="lead">Why not add a new transaction now?</p>
  </div>
</div>
<!-- /.row -->

<div class="row">
  <table id="last_transactions_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Date</th>
        <th>Supplier</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for row in table_rows %}
      <tr>
        {% for cell in row[1:-1] %}
        <td>{{ cell }}</td>
        {% endfor %}
        <td>
          <a href="{{ url_for('transactions.get_transaction', transaction_id=row[0]) }}" class="btn btn-info">
            View <i class="fa fa-chevron-right"></i>
          </a>
          {% if row[-1] %}
          <i class="fa fa-tag" style="color:mediumvioletred"></i>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
      <form id="add" method="post" action="{{ url_for('transactions.input_transaction') }}">
        <tr>
          <td>
            <input name="day" form="add" class="form-control" type="date" value="{{ today }}">
          </td>
          <td>
            <input name="supplier" form="add" class="suppliers form-control" id="supplier-input-id" type="text"
              placeholder="Supplier" list="suppliers">
            <datalist id="suppliers">
              {% for supplier in suppliers %}
              <option value="{{ supplier }}"></option>
              {% endfor %}
            </datalist>
          </td>
          <td>
            <input name="amount" form="add" class="form-control" type="text" placeholder="Amount">
          </td>
          <td>
            <input name="category" form="add" class="categories form-control" id="category-input-id" type="text"
              placeholder="Category" list="categories">
            <datalist id="categories">
              {% for category in categories %}
              <option value="{{ category }}"></option>
              {% endfor %}
            </datalist>

          </td>
          <td>
            <button type="submit" form="add" class="btn btn-success">
              Add <i class="fa fa-plus-circle"></i>
            </button>
          </td>
        </tr>
      </form>
    </tbody>
  </table>
</div>

<div class="row">

</div>
{% endblock %}

app/templates/person_add.html.j2
{% extends "base.html.j2" %}
{% block title %}Add a new person{% endblock %}

{% block scripts %}
<script type="text/javascript">
  $(document).ready(function () {
    $("#people-nav").removeClass("active");
    $("#transactions-nav").removeClass("active");
    $("#add-person-nav").addClass("active");
    $("#add-transaction-nav").removeClass("active");
    $("#export-nav").removeClass("active");
  });
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 text-center">
        <h1>Add a new person</h1>
        <p class="lead">Would you like to edit me or add some notes?</p>
    </div>
</div>

<div class="row">
  <form id="add" method="POST" action="{{ url_for('create_person_view') }}">
  <table id="table_id" class="table">
    <tbody>
      <tr>
        <th>Last name</th>
        <td>
          <input name="last_name" form="add" class="form-control" type="text" placeholder="Last name">
        </td>
        <th>First name</th>
        <td>
          <input name="first_name" form="add" class="form-control" type="text" placeholder="First name">
        </td>
      </tr>
      <tr>
        <th>Email</th>
        <td>
          <input name="email" form="add" class="suppliers form-control" type="text" placeholder="Email">
        </td>
        <th>Phone number</th>
        <td><input name="phone" form="add" class="form-control" type="text" placeholder="Phone number"></td>
      </tr>
      <tr>
        <th>Address</th>
        <td colspan="3">
          <textarea name="address" form="add" class="categories form-control"
            rows="3" placeholder="{{ '123 Street\nCity, Province\nPostal Code' }}"></textarea>
        </td>
      </tr>
      <tr>  
        <td></td>
        <td></td>
        <td></td>
        <td>
            <input type="submit" form="add" value="Add person" class="btn btn-success">
        </td>
      </tr>
    </tbody>
  </table>
  </form>
</div>
{% endblock %}

app/templates/person_table.html.j2
{% extends "base.html.j2" %}
{% block title %}All people{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function () {
    $("#people-nav").addClass("active");
    $("#transactions-nav").removeClass("active");
    $("#add-person-nav").removeClass("active");
    $("#add-transaction-nav").removeClass("active");
    $("#export-nav").removeClass("active");

    $("#table_id").DataTable({
      "stateSave": true,
      "lengthMenu": [50, 75, 100],
      "order": [],
    });
  });
</script>
{% endblock %}

{% block taskbar %}
<div class="navbar-collapse collapse">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" id="tax-nav" href="{{ url_for('all_receipts_pdf_view', year=year-1) }}">Tax receipts {{year - 1}}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="export-nav" href="{{ url_for('show_export_info') }}">Export</a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>All people</h1>
  </div>
</div>

<div>
  <table id="table_id" class="table table-striped table-bordered" cellspacing="0" style="width:100%">
    <thead>
      <tr>
        <th>Last name</th>
        <th>First name</th>
        <th>Phone number</th>
        <th>Email</th>
        <th>Total</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for person in persons %}
      <tr>
        <td>{{ person.last_name }}</td>
        <td>{{ person.first_name }}</td>
        <td>{{ person.phone }}</td>
        <td>{{ person.email }}</td>
        <td>{{ person.total | currency_format }}</td>
        <td>
          <a href="{{ url_for('person_summary_view', person_id=person.id) }}" class="btn btn-info btn-sm">
            View <i class="fa fa-chevron-right"></i>
          </a>
          {% if person.notes %}
          <i class="fa fa-tag" style="color:mediumvioletred"></i>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/pivot.html.j2
{% extends "base.html.j2" %}
{% block title %}Pivot table{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function () {

    $("#input-nav").removeClass("active");
    $("#view-nav").removeClass("active");
    $("#pivot-nav").addClass("active");
    $("#export-nav").removeClass("active");

    {% for obj in data %}
    $("#pivot{{ obj['year'] }}").DataTable({
      "stateSave": true,
      "lengthMenu": [50, 75, 100],
      "order": []
    });
    {% endfor %}

    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      $($.fn.dataTable.tables(true)).DataTable()
        .columns.adjust();
    });
  });
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Pivot table</h1>
    <p class="lead">So much better than Excel, isn't it?</p>
  </div>
</div>

<div>

  <nav style="margin-bottom: 20px;">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      {% for obj in data %}
      <a class="nav-item nav-link {% if obj['active'] %}active{% endif %}" id="nav-{{ obj['year'] }}-tab"
        data-toggle="tab" href="#nav-{{ obj['year'] }}" role="tab" aria-controls="nav-home"
        aria-selected="true">{{ obj['year'] }}</a>
      {% endfor %}
    </div>
  </nav>
  <div class="tab-content">
    {% for obj in data %}
    <div id="nav-{{ obj['year'] }}" role="tabpanel" class="tab-pane fade {% if obj['active'] %}show active{% endif %}"
      aria-labelledby="nav-{{ obj['year'] }}-tab">
      <table id="pivot{{ obj['year'] }}" class="table table-bordered table-hover table small" cellspacing="0"
        width="100%">
        <thead class="table-info">
          <tr>
            {% for c in obj['table_rows'][0] %}
            <th>{{ c }}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for row in obj['table_rows'][1:-1] %}
          <tr>
            <th>{{ row[0] }}</th>
            {% for cell in row[1:] %}
            <td>{{ cell }}</td>
            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
        <tfoot class="table-info">
          <tr>
            <th>{{ obj['table_rows'][-1][0] }}</th>
            {% for cell in obj['table_rows'][-1][1:] %}
            <td>{{ cell }}</td>
            {% endfor %}
          </tr>
        </tfoot>
      </table>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/report_upload.html.j2
{% extends "base.html.j2" %}
{% block title %}Parse Poynt Reports{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.js" 
  integrity="sha256-awEOL+kdrMJU/HUksRrTVHc6GA25FvDEIJ4KaEsFfG4=" 
  crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Parse reports</h1>
    <p class="lead">Upload the Excel files containing the reports to be parsed.</p>
  </div>
</div>

<div>
  <form method=post enctype=multipart/form-data>
    <p>
      <label for=transactions_file>Transactions report:</label>
      <input id=transactions_file type=file name=transactions>
    </p>

    <p>
      <label for=transactions_file>Items report:</label>
      <input id=items_file type=file name=items>
    </p>

    <input type=submit value=Upload>
  </form>
</div>

{% endblock %}

app/templates/table.html
{% extends "base.html" %}
{% block title %}All transactions{% endblock %}

{% block scripts %}
<script>
  $(document).ready(function () {
    $("#input-nav").removeClass("active");
    $("#view-nav").addClass("active");
    $("#pivot-nav").removeClass("active");

    $("#table_id").DataTable({
      "stateSave": true,
      "lengthMenu": [50, 75, 100],
      "order": [],
    });
  });
</script>

<script>
  $("#input-nav").removeClass("active");
  $("#view-nav").addClass("active");
  $("#pivot-nav").removeClass("active");
</script>
{% endblock %}

{% block taskbar %}
<a class="btn btn-success btn-sm mx-sm-1"
  href="{{ url_for('tables.download_table', format='csv', begin=begin, end=end)}}">
  <i class="fa fa-cloud-download"></i> CSV
</a>
<a class="btn btn-success btn-sm mx-sm-1"
  href="{{ url_for('tables.download_table', format='xlsx', begin=begin, end=end)}}">
  <i class="fa fa-cloud-download"></i> XLSX
</a>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>All your transactions</h1>
    <p class="lead">Search, filter and have fun!</p>
  </div>
</div>

<div class="row">
  <div class="col-lg-2 text-left">
    <p class="lead">
      <div class="dropdown show">
        <a class="btn btn-success btn-sm dropdown-toggle" href="#" role="button" id="dropdownMonth"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ month }}
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="?month=January">January</a>
          <a class="dropdown-item" href="?month=February">February</a>
          <a class="dropdown-item" href="?month=March">March</a>
          <a class="dropdown-item" href="?month=April">April</a>
          <a class="dropdown-item" href="?month=May">May</a>
          <a class="dropdown-item" href="?month=June">June</a>
          <a class="dropdown-item" href="?month=July">July</a>
          <a class="dropdown-item" href="?month=August">August</a>
          <a class="dropdown-item" href="?month=September">September</a>
          <a class="dropdown-item" href="?month=October">October</a>
          <a class="dropdown-item" href="?month=November">November</a>
          <a class="dropdown-item" href="?month=December">December</a>
        </div>
      </div>
    </p>
  </div>
  <div class="col-lg-8">
    <p class="lead">
      <form id="filter" class="form-inline justify-content-center">
        <input name="begin" form="filter" class="form-control-sm mr-sm-1" type="date" , value="{{ begin }}">
        <input name="end" form="filter" class="form-control-sm mr-sm-1" type="date" value="{{ end }}">
        <button type="submit" form="filter" class="btn btn-success btn-sm mr-sm-1">
          <i class="fa fa-search"></i>
        </button>
        <button type="reset" form="filter" class="btn btn-danger btn-sm mr-sm-1">
          <i class="fa fa-times"></i>
        </button>
      </form>
    </p>
  </div>
</div>

<div>
  <table id="table_id" class="table table-striped table-bordered" cellspacing="0" style="width:100%">
    <thead>
      <tr>
        <th>Date</th>
        <th>Supplier</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for row in table_rows %}
      <tr>
        {% for cell in row[1:-1] %}
        <td>{{ cell }}</td>
        {% endfor %}
        <td>
          <a href="{{ url_for('transactions.get_transaction', transaction_id=row[0]) }}" class="btn btn-success btn-sm">
            <i class="fa fa-pencil"></i> Edit
          </a>
          {% if row[-1] %}
          <i class="fa fa-tag" style="color:mediumvioletred"></i>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/transaction_data.html.j2
<!doctype html>
<html lang="en">

<body>
  <table id="data_table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Person ID</th>
        <th>Date</th>
        <th>Method</th>
        <th>Amount</th>
        <th>Accepted by</th>
        <th>Memo</th>
        <th>Created at</th>
        <th>Updated at</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
      <tr>
        <td>{{ transaction.id }}</td>
        <td>{{ transaction.person_id }}</td>
        <td>{{ transaction.date }}</td>
        <td>{{ transaction.method }}</td>
        <td>{{ transaction.amount }}</td>
        <td>{{ transaction.accepted_by }}</td>
        <td>{{ transaction.memo or '' }}</td>
        <td>{{ transaction.created_at }}</td>
        <td>{{ transaction.updated_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>